parameters:
    exception.codes:
        InvalidArgumentException: 400
        Symlex\Exception\AccessDeniedException: 403
        Symlex\Exception\NotFoundException: 404
        Symlex\Exception\MethodNotAllowedException: 405
        Exception: 500

    exception.messages:
        400: 'Bad request'
        401: 'Unauthorized'
        402: 'Payment Required'
        403: 'Forbidden'
        404: 'Not Found'
        405: 'Method Not Allowed'
        406: 'Not Acceptable'
        407: 'Proxy Authentication Required'
        408: 'Request Timeout'
        410: 'Gone'
        500: 'Looks like something went wrong!'
        503: 'Service unavailable - check server configuration'